// historic_heights.go
package neighborhoods

import (
	"time"

	"github.com/markbmullins/city-developer/pkg/models"
)

func GetHistoricHeightsNeighborhood() *models.Neighborhood {
	propertyIDs := make([]int, 0, len(HistoricResidential)+len(HistoricCommercial))
	for _, prop := range HistoricResidential {
		propertyIDs = append(propertyIDs, prop.ID)
	}
	for _, prop := range HistoricCommercial {
		propertyIDs = append(propertyIDs, prop.ID)
	}

	return &models.Neighborhood{
		ID:                   2,
		Name:                 "Historic Heights",
		PropertyIDs:          propertyIDs,
		AveragePropertyValue: 180000.0,
		RentBoostThreshold:   60.0, // 60% of properties need to be upgraded
		RentBoostAmount:      12.0, // 12% rent boost
	}
}

// HistoricResidential defines the residential properties for Historic Heights.
var HistoricResidential = []models.Property{
	{
		ID:                           21,
		Name:                         "Cobblestone Manor",
		Address:                      "1 Heritage Lane, Historic Heights",
		Description:                  "A charming single-family home with classic architectural details and spacious gardens.",
		Type:                         models.Residential,
		Subtype:                      models.SingleFamily,
		BaseRent:                     2500.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           22,
		Name:                         "Victorian Villa",
		Address:                      "12 Queen's Avenue, Historic Heights",
		Description:                  "A stunning townhome featuring ornate designs and a beautifully landscaped courtyard.",
		Type:                         models.Residential,
		Subtype:                      models.Townhome,
		BaseRent:                     3000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        600000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           23,
		Name:                         "Heritage Cottage",
		Address:                      "23 Heritage Road, Historic Heights",
		Description:                  "A quaint multifamily home with vintage charm and modern conveniences.",
		Type:                         models.Residential,
		Subtype:                      models.Multifamily,
		BaseRent:                     2800.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        580000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           24,
		Name:                         "Colonial Condos",
		Address:                      "34 Colonial Street, Historic Heights",
		Description:                  "Elegant condominiums with colonial-style exteriors and modern interiors.",
		Type:                         models.Residential,
		Subtype:                      models.Condo,
		BaseRent:                     3200.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        700000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           25,
		Name:                         "Old Town Apartments",
		Address:                      "45 Old Town Road, Historic Heights",
		Description:                  "Spacious apartments nestled in the heart of the historic district with easy access to local attractions.",
		Type:                         models.Residential,
		Subtype:                      models.Apartment,
		BaseRent:                     2900.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        580000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           26,
		Name:                         "Historic Haven",
		Address:                      "56 Heritage Circle, Historic Heights",
		Description:                  "A beautiful multifamily residence preserving historical architecture with modern updates.",
		Type:                         models.Residential,
		Subtype:                      models.Multifamily,
		BaseRent:                     3100.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        620000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           27,
		Name:                         "Colonial Heights",
		Address:                      "67 Colonial Avenue, Historic Heights",
		Description:                  "Luxurious condominiums with colonial elegance and top-tier amenities.",
		Type:                         models.Residential,
		Subtype:                      models.Condo,
		BaseRent:                     3400.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        750000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           28,
		Name:                         "Heritage Suites",
		Address:                      "78 Heritage Way, Historic Heights",
		Description:                  "Elegant suites combining historical charm with modern living spaces.",
		Type:                         models.Residential,
		Subtype:                      models.Apartment,
		BaseRent:                     3600.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        760000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           29,
		Name:                         "Old World Flats",
		Address:                      "89 Old World Street, Historic Heights",
		Description:                  "Classic apartments with antique finishes and modern amenities.",
		Type:                         models.Residential,
		Subtype:                      models.Apartment,
		BaseRent:                     3300.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        700000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           30,
		Name:                         "Classic Cornerstones",
		Address:                      "100 Heritage Boulevard, Historic Heights",
		Description:                  "Premium condominiums with historical architecture and modern luxuries.",
		Type:                         models.Residential,
		Subtype:                      models.Condo,
		BaseRent:                     3300.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicResidentialUpgradePaths(),
		Price:                        750000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  true,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
}

// HistoricCommercial defines the commercial properties for Historic Heights.
var HistoricCommercial = []models.Property{
	{
		ID:                           31,
		Name:                         "Old World Bistro",
		Address:                      "10 Heritage Street, Historic Heights",
		Description:                  "A charming bistro offering classic cuisine in a historic setting.",
		Type:                         models.Commercial,
		Subtype:                      models.Restaurant,
		BaseRent:                     7000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        1800000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           32,
		Name:                         "Heritage Bookstore",
		Address:                      "20 Library Lane, Historic Heights",
		Description:                  "A quaint bookstore specializing in antique and rare books.",
		Type:                         models.Commercial,
		Subtype:                      models.RetailStore,
		BaseRent:                     5000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        1200000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           33,
		Name:                         "Heritage Gymnasium",
		Address:                      "30 Fitness Avenue, Historic Heights",
		Description:                  "A gymnasium blending historic design with modern fitness equipment.",
		Type:                         models.Commercial,
		Subtype:                      models.Gym,
		BaseRent:                     10000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        2500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           34,
		Name:                         "Vintage Café",
		Address:                      "40 Retro Road, Historic Heights",
		Description:                  "A cozy café offering vintage-inspired beverages and pastries.",
		Type:                         models.Commercial,
		Subtype:                      models.Cafe,
		BaseRent:                     6000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        1400000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           35,
		Name:                         "Classic Cinema",
		Address:                      "50 Movie Lane, Historic Heights",
		Description:                  "A historic cinema offering a mix of classic and modern films.",
		Type:                         models.Commercial,
		Subtype:                      models.Museum,
		BaseRent:                     9000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        2200000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           36,
		Name:                         "Heritage Mall",
		Address:                      "60 Heritage Plaza, Historic Heights",
		Description:                  "A shopping mall preserving historic architecture with a mix of modern retailers.",
		Type:                         models.Commercial,
		Subtype:                      models.Mall,
		BaseRent:                     15000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        5000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           37,
		Name:                         "Nightlife Nexus",
		Address:                      "70 Party Avenue, Historic Heights",
		Description:                  "A vibrant nightlife spot with live music, dance floors, and premium drinks.",
		Type:                         models.Commercial,
		Subtype:                      models.NightClub,
		BaseRent:                     12000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        3000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           38,
		Name:                         "Artisan Gallery",
		Address:                      "80 Gallery Street, Historic Heights",
		Description:                  "A gallery showcasing handmade crafts and artisanal works from local artists.",
		Type:                         models.Commercial,
		Subtype:                      models.ArtGallery,
		BaseRent:                     8000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        2000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           39,
		Name:                         "Heritage Data Hub",
		Address:                      "90 Data Drive, Historic Heights",
		Description:                  "A secure data center blending historical aesthetics with modern technology.",
		Type:                         models.Commercial,
		Subtype:                      models.DataCenter,
		BaseRent:                     18000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        4500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
	{
		ID:                           40,
		Name:                         "Heritage Gymnasium",
		Address:                      "100 Fitness Boulevard, Historic Heights",
		Description:                  "A gymnasium offering a mix of classic and modern fitness equipment in a historic setting.",
		Type:                         models.Commercial,
		Subtype:                      models.Gym,
		BaseRent:                     10000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		UpgradeLevel:                 0,
		Upgrades:                     []models.Upgrade{},
		UpgradePaths:                 historicCommercialUpgradePaths(),
		Price:                        2500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		ProrateRent:                  false,
		NeighborhoodID:               2,
		UpgradedNeighborhoodRentBoost: 0.0,
	},
}

// Helper functions to define upgrade paths
func historicResidentialUpgradePaths() map[string][]models.Upgrade {
	return map[string][]models.Upgrade{
		"Restoration": {
			{
				Name:           "Structural Reinforcement",
				ID:             "rest_1",
				Level:          1,
				Cost:           7000.0,
				RentIncrease:   250.0,
				DaysToComplete: 10,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Facade Preservation",
				ID:             "rest_2",
				Level:          2,
				Cost:           14000.0,
				RentIncrease:   500.0,
				DaysToComplete: 20,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Historical Furnishing",
				ID:             "rest_3",
				Level:          3,
				Cost:           21000.0,
				RentIncrease:   800.0,
				DaysToComplete: 30,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Modern Amenities": {
			{
				Name:           "Smart Heating",
				ID:             "amen_1",
				Level:          1,
				Cost:           5000.0,
				RentIncrease:   200.0,
				DaysToComplete: 7,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Energy-efficient Lighting",
				ID:             "amen_2",
				Level:          2,
				Cost:           10000.0,
				RentIncrease:   400.0,
				DaysToComplete: 14,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "High-speed Internet",
				ID:             "amen_3",
				Level:          3,
				Cost:           15000.0,
				RentIncrease:   600.0,
				DaysToComplete: 21,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Luxury Enhancements": {
			{
				Name:           "Spa Bathroom",
				ID:             "lux_1",
				Level:          1,
				Cost:           8000.0,
				RentIncrease:   300.0,
				DaysToComplete: 10,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Designer Kitchen",
				ID:             "lux_2",
				Level:          2,
				Cost:           16000.0,
				RentIncrease:   600.0,
				DaysToComplete: 20,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Private Elevator",
				ID:             "lux_3",
				Level:          3,
				Cost:           24000.0,
				RentIncrease:   900.0,
				DaysToComplete: 30,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
	}
}

func historicCommercialUpgradePaths() map[string][]models.Upgrade {
	return map[string][]models.Upgrade{
		"Facility Enhancements": {
			{
				Name:           "Extended Hours",
				ID:             "fac_1",
				Level:          1,
				Cost:           8000.0,
				RentIncrease:   300.0,
				DaysToComplete: 10,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Advanced Security Systems",
				ID:             "fac_2",
				Level:          2,
				Cost:           16000.0,
				RentIncrease:   600.0,
				DaysToComplete: 20,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Climate Control",
				ID:             "fac_3",
				Level:          3,
				Cost:           24000.0,
				RentIncrease:   900.0,
				DaysToComplete: 30,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Operational Upgrades": {
			{
				Name:           "Automated Inventory",
				ID:             "op_1",
				Level:          1,
				Cost:           6000.0,
				RentIncrease:   250.0,
				DaysToComplete: 8,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Digital POS System",
				ID:             "op_2",
				Level:          2,
				Cost:           12000.0,
				RentIncrease:   500.0,
				DaysToComplete: 16,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Customer Loyalty Program",
				ID:             "op_3",
				Level:          3,
				Cost:           18000.0,
				RentIncrease:   750.0,
				DaysToComplete: 24,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Brand Expansion": {
			{
				Name:           "Marketing Campaign",
				ID:             "brand_1",
				Level:          1,
				Cost:           9000.0,
				RentIncrease:   350.0,
				DaysToComplete: 12,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "New Product Line",
				ID:             "brand_2",
				Level:          2,
				Cost:           18000.0,
				RentIncrease:   700.0,
				DaysToComplete: 24,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "International Expansion",
				ID:             "brand_3",
				Level:          3,
				Cost:           27000.0,
				RentIncrease:   1050.0,
				DaysToComplete: 36,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
	}
}
