// tech_valley.go
package neighborhoods

import (
	"time"

	"github.com/markbmullins/city-developer/pkg/components"
)
func GetTechValleyNeighborhood() *components.Neighborhood {
	propertyIDs := make([]int, 0, len(TechResidential)+len(TechCommercial))
	for _, prop := range TechResidential {
		propertyIDs = append(propertyIDs, prop.ID)
	}
	for _, prop := range TechCommercial {
		propertyIDs = append(propertyIDs, prop.ID)
	}

	return &components.Neighborhood{
		ID:                   3,
		Name:                 "Tech Valley",
		PropertyIDs:          propertyIDs,
		AveragePropertyValue: 0.0,
		RentBoostThreshold:   55.0, // 55% of properties need to be upgraded
		RentBoostPercent:      15.0, // 15% rent boost
	}
}

func GetTechValleyProperties() []components.Property {
	return append(TechResidential, TechCommercial...)
}

var TechResidential = []components.Property{
	{
		ID:                           41,
		Name:                         "Futuristic Flats",
		Address:                      "100 Innovation Drive, Tech Valley",
		Description:                  "Modern apartments with cutting-edge technology and smart home features.",
		Type:                         components.Residential,
		Subtype:                      components.Apartment,
		BaseRent:                     3200.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        700000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           42,
		Name:                         "Silicon Heights",
		Address:                      "200 Silicon Avenue, Tech Valley",
		Description:                  "Condominiums equipped with the latest smart technologies and energy-efficient systems.",
		Type:                         components.Residential,
		Subtype:                      components.Condo,
		BaseRent:                     4000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        1200000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           43,
		Name:                         "Quantum Quarters",
		Address:                      "300 Quantum Road, Tech Valley",
		Description:                  "High-tech multifamily residences with integrated IoT devices and automated systems.",
		Type:                         components.Residential,
		Subtype:                      components.Multifamily,
		BaseRent:                     3500.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        900000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           44,
		Name:                         "Circuit City Condos",
		Address:                      "400 Circuit Lane, Tech Valley",
		Description:                  "Condominiums with smart glass windows and integrated home automation systems.",
		Type:                         components.Residential,
		Subtype:                      components.Condo,
		BaseRent:                     3800.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        1150000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           45,
		Name:                         "Neon Nights Apartments",
		Address:                      "500 Neon Street, Tech Valley",
		Description:                  "Apartments featuring vibrant lighting and smart security systems.",
		Type:                         components.Residential,
		Subtype:                      components.Apartment,
		BaseRent:                     2900.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        680000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           46,
		Name:                         "Tech Tower Apartments",
		Address:                      "600 Tech Tower Road, Tech Valley",
		Description:                  "High-rise apartments with panoramic views and integrated tech solutions.",
		Type:                         components.Residential,
		Subtype:                      components.Apartment,
		BaseRent:                     3300.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        800000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           47,
		Name:                         "Byte Boulevard Condos",
		Address:                      "700 Byte Boulevard, Tech Valley",
		Description:                  "Condominiums with advanced networking infrastructure and smart home integrations.",
		Type:                         components.Residential,
		Subtype:                      components.Condo,
		BaseRent:                     3600.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        850000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           48,
		Name:                         "Quantum Quarters",
		Address:                      "800 Quantum Street, Tech Valley",
		Description:                  "Apartments with quantum computing units and AI-driven home management.",
		Type:                         components.Residential,
		Subtype:                      components.Apartment,
		BaseRent:                     4000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        1000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           49,
		Name:                         "Circuit City Condos",
		Address:                      "900 Circuit Lane, Tech Valley",
		Description:                  "Condominiums with smart glass windows and integrated home automation systems.",
		Type:                         components.Residential,
		Subtype:                      components.Condo,
		BaseRent:                     4400.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        1400000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           50,
		Name:                         "Circuit City Condos",
		Address:                      "1000 Circuit Way, Tech Valley",
		Description:                  "Condominiums equipped with the latest smart technologies and energy-efficient systems.",
		Type:                         components.Residential,
		Subtype:                      components.Condo,
		BaseRent:                     4400.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techResidentialUpgradePaths(),
		Price:                        1400000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
}

var TechCommercial = []components.Property{
	{
		ID:                           51,
		Name:                         "Innovation Hub",
		Address:                      "10 Innovation Drive, Tech Valley",
		Description:                  "A central hub for startups and tech companies with collaborative workspaces and modern facilities.",
		Type:                         components.Commercial,
		Subtype:                      components.OfficeSpace,
		BaseRent:                     13000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        3500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           52,
		Name:                         "Cyber Café",
		Address:                      "20 Cyber Lane, Tech Valley",
		Description:                  "A high-tech café offering free Wi-Fi, smart devices, and a collaborative environment for tech enthusiasts.",
		Type:                         components.Commercial,
		Subtype:                      components.Cafe,
		BaseRent:                     6000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        1600000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           53,
		Name:                         "Tech Plaza",
		Address:                      "30 Tech Plaza, Tech Valley",
		Description:                  "A modern office space with flexible leasing options and state-of-the-art facilities.",
		Type:                         components.Commercial,
		Subtype:                      components.OfficeSpace,
		BaseRent:                     11000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        3200000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           54,
		Name:                         "Techno Bar",
		Address:                      "40 Techno Street, Tech Valley",
		Description:                  "A bar with cutting-edge lighting and sound systems, offering a unique nightlife experience.",
		Type:                         components.Commercial,
		Subtype:                      components.Bar,
		BaseRent:                     9000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        2000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           55,
		Name:                         "Cyber Hub",
		Address:                      "50 Cyber Drive, Tech Valley",
		Description:                  "A coworking space designed for tech startups with high-speed internet and collaborative zones.",
		Type:                         components.Commercial,
		Subtype:                      components.OfficeSpace,
		BaseRent:                     14000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        4000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           56,
		Name:                         "Virtual Reality Lounge",
		Address:                      "60 VR Avenue, Tech Valley",
		Description:                  "A lounge offering virtual reality experiences and gaming for tech enthusiasts.",
		Type:                         components.Commercial,
		Subtype:                      components.Amusement,
		BaseRent:                     10000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        2500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           57,
		Name:                         "Techno Nightclub",
		Address:                      "70 Techno Boulevard, Tech Valley",
		Description:                  "A high-energy nightclub featuring the latest in sound and lighting technology.",
		Type:                         components.Commercial,
		Subtype:                      components.NightClub,
		BaseRent:                     13000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        3500000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           58,
		Name:                         "Data Center Hub",
		Address:                      "80 Data Drive, Tech Valley",
		Description:                  "A secure data center providing cloud services and storage solutions with high redundancy.",
		Type:                         components.Commercial,
		Subtype:                      components.DataCenter,
		BaseRent:                     25000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        7000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           59,
		Name:                         "Quantum Research Lab",
		Address:                      "90 Quantum Plaza, Tech Valley",
		Description:                  "A cutting-edge research lab focused on quantum computing and AI development.",
		Type:                         components.Commercial,
		Subtype:                      components.Factory,
		BaseRent:                     20000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        6000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
	{
		ID:                           60,
		Name:                         "Data Center Hub",
		Address:                      "1000 Data Center Road, Tech Valley",
		Description:                  "A secure data center providing cloud services and storage solutions.",
		Type:                         components.Commercial,
		Subtype:                      components.DataCenter,
		BaseRent:                     25000.0,
		RentBoost:                    0.0,
		Owned:                        false,
		Upgrades:                     []components.Upgrade{},
		UpgradePaths:                 techCommercialUpgradePaths(),
		Price:                        7000000.0,
		PlayerID:                     0,
		OccupancyRate:                0.0,
		TenantSatisfaction:           0,
		PurchaseDate:                 time.Time{},
		NeighborhoodID:               3,
	},
}

func techResidentialUpgradePaths() map[string][]components.Upgrade {
	return map[string][]components.Upgrade{
		"Smart Living": {
			{
				Name:           "Basic Smart Home",
				ID:             "smart_1",
				Level:          1,
				Cost:           6000.0,
				RentIncrease:   250.0,
				DaysToComplete: 7,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Advanced Smart Systems",
				ID:             "smart_2",
				Level:          2,
				Cost:           12000.0,
				RentIncrease:   500.0,
				DaysToComplete: 14,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "AI Integration",
				ID:             "smart_3",
				Level:          3,
				Cost:           18000.0,
				RentIncrease:   800.0,
				DaysToComplete: 21,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Energy Efficiency": {
			{
				Name:           "Solar Panels",
				ID:             "ene_1",
				Level:          1,
				Cost:           7000.0,
				RentIncrease:   300.0,
				DaysToComplete: 10,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Energy-efficient Windows",
				ID:             "ene_2",
				Level:          2,
				Cost:           14000.0,
				RentIncrease:   600.0,
				DaysToComplete: 20,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "High-efficiency HVAC",
				ID:             "ene_3",
				Level:          3,
				Cost:           21000.0,
				RentIncrease:   900.0,
				DaysToComplete: 30,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Luxury Upgrades": {
			{
				Name:           "Spa Bathroom",
				ID:             "lux_1",
				Level:          1,
				Cost:           10000.0,
				RentIncrease:   400.0,
				DaysToComplete: 10,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Designer Kitchen",
				ID:             "lux_2",
				Level:          2,
				Cost:           20000.0,
				RentIncrease:   800.0,
				DaysToComplete: 20,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Smart Mirror System",
				ID:             "lux_3",
				Level:          3,
				Cost:           30000.0,
				RentIncrease:   1200.0,
				DaysToComplete: 30,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
	}
}

func techCommercialUpgradePaths() map[string][]components.Upgrade {
	return map[string][]components.Upgrade{
		"Facility Enhancements": {
			{
				Name:           "Automated Lighting",
				ID:             "fac_1",
				Level:          1,
				Cost:           10000.0,
				RentIncrease:   500.0,
				DaysToComplete: 10,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Climate Control Systems",
				ID:             "fac_2",
				Level:          2,
				Cost:           20000.0,
				RentIncrease:   1000.0,
				DaysToComplete: 20,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Automated Cleaning Robots",
				ID:             "fac_3",
				Level:          3,
				Cost:           30000.0,
				RentIncrease:   1500.0,
				DaysToComplete: 30,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Tech Upgrades": {
			{
				Name:           "High-speed Networking",
				ID:             "tech_1",
				Level:          1,
				Cost:           12000.0,
				RentIncrease:   600.0,
				DaysToComplete: 12,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Smart Surveillance",
				ID:             "tech_2",
				Level:          2,
				Cost:           24000.0,
				RentIncrease:   1200.0,
				DaysToComplete: 24,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "AI Security Systems",
				ID:             "tech_3",
				Level:          3,
				Cost:           36000.0,
				RentIncrease:   1800.0,
				DaysToComplete: 36,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
		"Operational Efficiency": {
			{
				Name:           "Automated Inventory Management",
				ID:             "op_1",
				Level:          1,
				Cost:           8000.0,
				RentIncrease:   400.0,
				DaysToComplete: 8,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "Robotic Assistants",
				ID:             "op_2",
				Level:          2,
				Cost:           16000.0,
				RentIncrease:   800.0,
				DaysToComplete: 16,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
			{
				Name:           "AI Customer Support",
				ID:             "op_3",
				Level:          3,
				Cost:           24000.0,
				RentIncrease:   1200.0,
				DaysToComplete: 24,
				PurchaseDate:   time.Time{},
				Prerequisite:   nil,
				Applied:        false,
			},
		},
	}
}
